packages:
  - "packages/*"
  - "packages/cre/attest"
  - "apps/*"
allowBuilds:
  esbuild: true
  keccak: false
minimumReleaseAgeExclude:
  - '@peeramid-labs/multipass-client@1.1.0'
  - '@peeramid-labs/multipass@1.1.0'
